### ISSUE TITLE
USER STORY: As a site user I want to comment on other's recipes

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#10]
EPIC: User Comments

As a **site user** I can **comment on another blog post** so that **I can ask questions or leave feedback**

**Acceptance Criteria**

To Comment:
I must be a logged in user
I can click on a comment section and leave a comment
The comment will be available for all users to view in the comment section of that blog/recipe

To Receive Comment:

- [ ] I must a logged in user with recipes on my profile
- [ ] There are comments sections under my blog recipes for other users to comment
- [ ] When a comment is submitted I receive a notification
- [ ] I can view the comment and have the option to delete or reply if required

**Tasks**

- [ ] Add a comment option div and button to "leave a comment"
- [ ] Only allow logged in users to leave comments
- [ ] Develop a notification system to inform users when a comment has been left on one of their recipes
- [ ] Allow the owner of the blog/recipe to delete or reply to a comment
- [ ] No other user can delete or reply to another user's comments

**Comment by DaniCarmo** [comment]
maybe a future feature to implement but not right now
