### ISSUE TITLE
USER STORY: As a site user I can view a recipe

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#3]
EPIC: View Recipes

As a **Site User** I can **view recipes** so that **I can follow them at home**

**Acceptance Criteria**

- [ ] Given that I am a user on the site
- [ ] When I navigate to the recipes page
- [ ] Then I am presented with a list of the recipes available
- [ ] When I click on a recipe
- [ ] Then I am presented with the full recipe details

**Tasks**

- [ ]  Task 1 - Develop a link all users can access to the recipes page
- [ ]  Task 2 - The recipes page should list all of the recipes
- [ ]  Task 3 - Develop recipe cards that display a summary of the recipe they relate to
- [ ]  Task 4 - Develop a link from the card to the full recipe details page
- [ ]  Task 5 - Develop a full recipe details page that provides the full details for the recipe
