### ISSUE TITLE
USER STORY: As a site user I can delete a recipe

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#5]
EPIC: Delete Recipe

As a **rsite user** I can **delete a recipe that I have created** so that **I can remove it from the site**

**Acceptance Criteria**

- [ ] Given that I am a registered user who is logged in, and has created a recipe
- [ ] When I navigate to the recipe that I would like to delete
- [ ] Then I have the option to delete the recipe
- [ ] Then I receive a confirmation window to confirm that I really want to delete the recipe
- [ ] Then the recipe is deleted from the system

**Tasks**

- [ ]  Task 1 - Develop a delete recipe button that appears on the recipe page when the logged in user is the recipe author
- [ ]  Task 2 - Develop a deletion confirmation window that appears when the user clicks the delete recipe button
- [ ]  Task 3 - Develop the code that deletes the recipe record when the user confirms the deletion
