### ISSUE TITLE
USER STORY: As a site user I want to identify the recipe calories

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#6]
EPIC: View Calories

As a **site user* I can **view the calories** so that **I can keep track of my daily calory intake**

**Acceptance Criteria**

- [ ] When I am logged in as user
- [ ] I can click on the recipe and see the calories at the end of the recipe

**Tasks**

- [ ] Once recipe has been created, add in calorie section per recipe
