### ISSUE TITLE
USER STORY: As a user I want to be able to search for recipes

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#7]
EPIC: Search Recipes

As a **site user** I can **search through recipes** so that **I can find something that is sepicific to my liking**

**Acceptance Criteria**

- [ ] When I enter the recipe section of the site
- [ ] Then I have options to navigate to different recipe sections
- [ ] I also have the option to enter a searchword to find what I'm looking for
- [ ] Then I can access the full recipe details by clicking on the recipe that is returned from my search

**Tasks**

- [ ]  Task 1 – Develop a link to the recipe section on the main homepage
- [ ]  Task 2 – Develop a set link that produces filtered recipe results – such as beef, chicken, curries, cocktails
