### ISSUE TITLE
USER STORY: As a site user I want to ceate and log in to my account

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#8]
EPIC: Create Account/Login

As a **site user** I can **create and account and log in when visiting the site** so that **I can add, edit and delete my recipes**

**Acceptance Criteria**

- [ ] Given that I am a registered user, who is not logged in
- [ ] When I navigate to the sign in page I enter my credentials correctly and click login
- [ ] Then I am signed into my account
- [ ] I also have the option to logout

**Tasks**

- [ ]  Task 1 – Develop the ability for users to sign into their account
- [ ]  Task 2 – Develop a sign in form to capture user sign in details
- [ ]  Task 3 – Develop form validation to ensure the data is correct
- [ ]  Task 4 – Develop a method to validate the data entered matches a user account
- [ ]  Task 5 – Develop a link for users to sign out of their account – should be accessible from all pages – suggest within nav bar, user account section
