### ISSUE TITLE
USER STORY: As a sure I want to create a daily meal plan with reciupes from the site

### ISSUE THREAD

**Issue by DaniCarmo** [DaniCarmo/Yummy-Blog-p4#9]
EPIC: Meal Planner

As a **site user** I can **save recipes in a meal planner** so that **I can create a daily meal plan to follow for each day, week, month, etc**

**Acceptance Criteria**

- [ ]  When I am a registered user and logged in
- [ ] I navigate to my profile and can click on "Meals"
- [ ] I can select a day of the current month and add meals for that day
- [ ] I can view these saved daily meals whenever I return to the meal planner

**Tasks**

- [ ] Create a new meal planner page off user profile page
- [ ] Current days and month will show up as options to chose from
- [ ] Provide a meal suggestion and a search bar for meals
- [ ] User can select 1 - 3 meals per day that will save within that day's plan
